[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/worker/Dockerfile"
watchPatterns = ["/apps/worker/**", "/packages/**", "/package.json", "/bun.lock", "/vite.config.ts"]

[deploy]
startCommand = "node --enable-source-maps dist/index.mjs"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
