/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as appadminRouteRouteImport } from './routes/(app)/(admin)/route'
import { Route as appCollaborationRouteImport } from './routes/(app)/collaboration'
import { Route as appControlRouteImport } from './routes/(app)/control'
import { Route as appLibraryRouteImport } from './routes/(app)/library'
import { Route as appTemplatesRouteImport } from './routes/(app)/templates'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as appadminAdminRouteImport } from './routes/(app)/(admin)/admin'
import { Route as appChatChatIdRouteImport } from './routes/(app)/chat.$chatId'
import { Route as appProjectsIndexRouteImport } from './routes/(app)/projects.index'
import { Route as appProjectsProjectIdRouteImport } from './routes/(app)/projects.$projectId'
import { Route as appadminAdminSettingsRouteImport } from './routes/(app)/(admin)/admin/settings'
import { Route as appadminAdminSettingsAuthRouteImport } from './routes/(app)/(admin)/admin/settings/auth'
import { Route as appProjectsProjectIdPiSessionIdRouteImport } from './routes/(app)/projects.$projectId_.pi.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const appadminRouteRoute = appadminRouteRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => appRouteRoute,
} as any)
const appCollaborationRoute = appCollaborationRouteImport.update({
  id: '/collaboration',
  path: '/collaboration',
  getParentRoute: () => appRouteRoute,
} as any)
const appControlRoute = appControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => appRouteRoute,
} as any)
const appLibraryRoute = appLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => appRouteRoute,
} as any)
const appTemplatesRoute = appTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => appRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => authRouteRoute,
} as any)
const appadminAdminRoute = appadminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => appadminRouteRoute,
} as any)
const appChatChatIdRoute = appChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => appRouteRoute,
} as any)
const appProjectsIndexRoute = appProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => appRouteRoute,
} as any)
const appProjectsProjectIdRoute = appProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => appRouteRoute,
} as any)
const appadminAdminSettingsRoute = appadminAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appadminAdminRoute,
} as any)
const appadminAdminSettingsAuthRoute =
  appadminAdminSettingsAuthRouteImport.update({
    id: '/auth',
    path: '/auth',
    getParentRoute: () => appadminAdminSettingsRoute,
  } as any)
const appProjectsProjectIdPiSessionIdRoute =
  appProjectsProjectIdPiSessionIdRouteImport.update({
    id: '/projects/$projectId_/pi/$sessionId',
    path: '/projects/$projectId/pi/$sessionId',
    getParentRoute: () => appRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/collaboration': typeof appCollaborationRoute
  '/control': typeof appControlRoute
  '/library': typeof appLibraryRoute
  '/templates': typeof appTemplatesRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/admin': typeof appadminAdminRouteWithChildren
  '/chat/$chatId': typeof appChatChatIdRoute
  '/projects/$projectId': typeof appProjectsProjectIdRoute
  '/projects/': typeof appProjectsIndexRoute
  '/admin/settings': typeof appadminAdminSettingsRouteWithChildren
  '/admin/settings/auth': typeof appadminAdminSettingsAuthRoute
  '/projects/$projectId/pi/$sessionId': typeof appProjectsProjectIdPiSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/collaboration': typeof appCollaborationRoute
  '/control': typeof appControlRoute
  '/library': typeof appLibraryRoute
  '/templates': typeof appTemplatesRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/admin': typeof appadminAdminRouteWithChildren
  '/chat/$chatId': typeof appChatChatIdRoute
  '/projects/$projectId': typeof appProjectsProjectIdRoute
  '/projects': typeof appProjectsIndexRoute
  '/admin/settings': typeof appadminAdminSettingsRouteWithChildren
  '/admin/settings/auth': typeof appadminAdminSettingsAuthRoute
  '/projects/$projectId/pi/$sessionId': typeof appProjectsProjectIdPiSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/(app)/(admin)': typeof appadminRouteRouteWithChildren
  '/(app)/collaboration': typeof appCollaborationRoute
  '/(app)/control': typeof appControlRoute
  '/(app)/library': typeof appLibraryRoute
  '/(app)/templates': typeof appTemplatesRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(app)/(admin)/admin': typeof appadminAdminRouteWithChildren
  '/(app)/chat/$chatId': typeof appChatChatIdRoute
  '/(app)/projects/$projectId': typeof appProjectsProjectIdRoute
  '/(app)/projects/': typeof appProjectsIndexRoute
  '/(app)/(admin)/admin/settings': typeof appadminAdminSettingsRouteWithChildren
  '/(app)/(admin)/admin/settings/auth': typeof appadminAdminSettingsAuthRoute
  '/(app)/projects/$projectId_/pi/$sessionId': typeof appProjectsProjectIdPiSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manifest.webmanifest'
    | '/collaboration'
    | '/control'
    | '/library'
    | '/templates'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/admin'
    | '/chat/$chatId'
    | '/projects/$projectId'
    | '/projects/'
    | '/admin/settings'
    | '/admin/settings/auth'
    | '/projects/$projectId/pi/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manifest.webmanifest'
    | '/collaboration'
    | '/control'
    | '/library'
    | '/templates'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/admin'
    | '/chat/$chatId'
    | '/projects/$projectId'
    | '/projects'
    | '/admin/settings'
    | '/admin/settings/auth'
    | '/projects/$projectId/pi/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(auth)'
    | '/manifest.webmanifest'
    | '/(app)/(admin)'
    | '/(app)/collaboration'
    | '/(app)/control'
    | '/(app)/library'
    | '/(app)/templates'
    | '/(auth)/login'
    | '/(auth)/reset-password'
    | '/(auth)/signup'
    | '/(auth)/verify-email'
    | '/(app)/(admin)/admin'
    | '/(app)/chat/$chatId'
    | '/(app)/projects/$projectId'
    | '/(app)/projects/'
    | '/(app)/(admin)/admin/settings'
    | '/(app)/(admin)/admin/settings/auth'
    | '/(app)/projects/$projectId_/pi/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(admin)': {
      id: '/(app)/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appadminRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/collaboration': {
      id: '/(app)/collaboration'
      path: '/collaboration'
      fullPath: '/collaboration'
      preLoaderRoute: typeof appCollaborationRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/control': {
      id: '/(app)/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof appControlRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/library': {
      id: '/(app)/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof appLibraryRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/templates': {
      id: '/(app)/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof appTemplatesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/(admin)/admin': {
      id: '/(app)/(admin)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof appadminAdminRouteImport
      parentRoute: typeof appadminRouteRoute
    }
    '/(app)/chat/$chatId': {
      id: '/(app)/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof appChatChatIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/projects/': {
      id: '/(app)/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof appProjectsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/projects/$projectId': {
      id: '/(app)/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof appProjectsProjectIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(admin)/admin/settings': {
      id: '/(app)/(admin)/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof appadminAdminSettingsRouteImport
      parentRoute: typeof appadminAdminRoute
    }
    '/(app)/(admin)/admin/settings/auth': {
      id: '/(app)/(admin)/admin/settings/auth'
      path: '/auth'
      fullPath: '/admin/settings/auth'
      preLoaderRoute: typeof appadminAdminSettingsAuthRouteImport
      parentRoute: typeof appadminAdminSettingsRoute
    }
    '/(app)/projects/$projectId_/pi/$sessionId': {
      id: '/(app)/projects/$projectId_/pi/$sessionId'
      path: '/projects/$projectId/pi/$sessionId'
      fullPath: '/projects/$projectId/pi/$sessionId'
      preLoaderRoute: typeof appProjectsProjectIdPiSessionIdRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appadminAdminSettingsRouteChildren {
  appadminAdminSettingsAuthRoute: typeof appadminAdminSettingsAuthRoute
}

const appadminAdminSettingsRouteChildren: appadminAdminSettingsRouteChildren = {
  appadminAdminSettingsAuthRoute: appadminAdminSettingsAuthRoute,
}

const appadminAdminSettingsRouteWithChildren =
  appadminAdminSettingsRoute._addFileChildren(
    appadminAdminSettingsRouteChildren,
  )

interface appadminAdminRouteChildren {
  appadminAdminSettingsRoute: typeof appadminAdminSettingsRouteWithChildren
}

const appadminAdminRouteChildren: appadminAdminRouteChildren = {
  appadminAdminSettingsRoute: appadminAdminSettingsRouteWithChildren,
}

const appadminAdminRouteWithChildren = appadminAdminRoute._addFileChildren(
  appadminAdminRouteChildren,
)

interface appadminRouteRouteChildren {
  appadminAdminRoute: typeof appadminAdminRouteWithChildren
}

const appadminRouteRouteChildren: appadminRouteRouteChildren = {
  appadminAdminRoute: appadminAdminRouteWithChildren,
}

const appadminRouteRouteWithChildren = appadminRouteRoute._addFileChildren(
  appadminRouteRouteChildren,
)

interface appRouteRouteChildren {
  appadminRouteRoute: typeof appadminRouteRouteWithChildren
  appCollaborationRoute: typeof appCollaborationRoute
  appControlRoute: typeof appControlRoute
  appLibraryRoute: typeof appLibraryRoute
  appTemplatesRoute: typeof appTemplatesRoute
  appChatChatIdRoute: typeof appChatChatIdRoute
  appProjectsProjectIdRoute: typeof appProjectsProjectIdRoute
  appProjectsIndexRoute: typeof appProjectsIndexRoute
  appProjectsProjectIdPiSessionIdRoute: typeof appProjectsProjectIdPiSessionIdRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appadminRouteRoute: appadminRouteRouteWithChildren,
  appCollaborationRoute: appCollaborationRoute,
  appControlRoute: appControlRoute,
  appLibraryRoute: appLibraryRoute,
  appTemplatesRoute: appTemplatesRoute,
  appChatChatIdRoute: appChatChatIdRoute,
  appProjectsProjectIdRoute: appProjectsProjectIdRoute,
  appProjectsIndexRoute: appProjectsIndexRoute,
  appProjectsProjectIdPiSessionIdRoute: appProjectsProjectIdPiSessionIdRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignupRoute: typeof authSignupRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignupRoute: authSignupRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
